### PR TITLE
Fixes for tradeID and dependency updates

### PR DESCRIPTION
**Pull request by jSydorowicz21**
**Overview:**
This PR includes fixes to the tradeID properties in orders.go, also includes package updates and a few typo corrections along with an instrument.go update commit I found useful from @shenxu83

**Key Changes:**

1. **Updates in `orders.go`:**
   - Added TradeID property to OrderPayload
   - Fixed the capitalization on all tradeID properties so they are marshalled and unmarshalled properly

2. **Updates in `instrument.go`:**
   - Replaced `requestAndUnmarshal` with `getAndUnmarshal` for improved request handling in `GetTimeToCandles` and `GetTimeFromCandles` functions.
   - This change ensures uniformity in the codebase.

3. **General updates**
  - Updated godotenv to v1.5.1

**Files Affected:**
- `trade.go`
- `go.mod`
- `go.sum`
- `instrument.go`

### CODE REVIEW

**Comment by jSydorowicz21** [comment]
Hey there @AwolDes, Are you still maintaining this project? I've ran into a couple problems through using the project that I'd love to help fixup if you are! Otherwise if not I can fork and maintain that version

**Review by AwolDes — APPROVED** [review]

**Comment by AwolDes** [comment]
> Hey there @AwolDes, Are you still maintaining this project? I've ran into a couple problems through using the project that I'd love to help fixup if you are! Otherwise if not I can fork and maintain that version

Thanks for putting up the PR! I should update the README - I am no longer maintaining this codebase & unfortunately had notifications turned off for a long time, missing community contributions.

My days of Algotrading are over for now, if you fork it happy to update th README to point towards your version.

Edit: alternatively I can add you to this repo as maintainer

**Comment by jSydorowicz21** [comment]
> Thanks for putting up the PR! I should update the README - I am no longer maintaining this codebase & unfortunately had notifications turned off for a long time, missing community contributions.
> 
> My days of Algotrading are over for now, if you fork it happy to update the README to point towards your version.
> 
> Edit: alternatively I can add you to this repo as maintainer

I'm up for being added as a maintainer, currently go reports 11 projects import the repo so might as well pay the favor forward and help those 11 people since this package helped me jump start my algo trading project!

**Comment by AwolDes** [comment]
@jSydorowicz21 added you as a collaborator

**Pull request merged**
