### PR TITLE
Streaming capabilities, testing suite and bug fixes

### PR DESCRIPTION
**Pull request by jSydorowicz21**
## New Features
1. Added `streaming.go` to implement **streaming** functionality for real-time data.
2. Implemented streaming for prices and transactions.
3. Enhanced order submission capabilities:
   - Users can now submit orders with additional properties in the `OrderBody` struct:
     - `ReplacesOrderID`: Allows specifying an order to be replaced
     - `ReplacedByOrderID`: Indicates the ID of the order that replaced this order
     - `TriggerCondition`: Specifies the condition for triggering the order
     - `GTDTime`: Sets the "Good Till Date" time for the order
     - `PartialFill`: Controls whether partial fills are allowed
     - `Distance`: Sets the distance for trailing stop orders
     - `TakeProfitOnFill`: Set a take profit order to be created when the trade is opened.
     - `StopLossOnFill`: Set a stop loss order to be created when the trade is opened.
     - `GuaranteedStopLossOnFill`: Set a guaranteed stop loss order to be created when the trade is opened.
     - `TrailingStopLossOnFill`: Set a trailing stop loss order to be created when the trade is opened.
   - The `OrderResponse` struct now includes more detailed information about order creation and filling transactions.
   - The `OrderInfo` struct provides comprehensive details about orders, including new fields like `TradeReducedID`, `TradeClosedIDs`, and `CancellingTransactionID`.

4. Expanded trade information:
   - The `ReceivedTrades` and `ReceivedTrade` structs now include additional fields such as `CurrentUnits`, `Financing`, `InitialUnits`, `OpenTime`, `RealizedPL`, and `UnrealizedPL`.
   - Added `FullPrice` and `PriceLevel` structs for more detailed pricing information.
   
   
5. Added `GetOrderState` method to infer an orders status based on structs returned

## Tests
1. Added comprehensive test files for the first time:
   - `account_test.go`
   - `streaming_test.go`
   - `pricing_test.go`
   - `instrument_test.go`
   - `trades_test.go`
   - `transactions_test.go`
   - `positions_test.go`
   - `orders_test.go`

2. Implemented tests for all major functionalities, including new streaming features.
3. Added `TestOrderIntegration` in `orders_test.go` to use dynamic pricing and validate real requests work as expected.
4. Added `TestStreamIntegration` in `streaming_test.go` to validate real data returns in streams

## Bug Fixes
1. Fixed a bug in `GetAccountInstruments` that made it always return an empty array of instruments.

## Enhancements
1. Significantly expanded the `OrderBody`, `OrderResponse`, and `OrderInfo` structs in `orders.go` to include more properties supported by the OANDA API:
   - Added fields like `ReplacesOrderID`, `ReplacedByOrderID`, `TriggerCondition`, `GTDTime`, `PartialFill`, and `Distance`.
   - Enhanced `OrderCreateTransaction` and `OrderFillTransaction` sub-structures with additional fields.

2. Updated `ReceivedTrades`, `ReceivedTrade`, and `ModifiedTrade` structs in `trades.go` to include additional fields for more comprehensive trade information including trailing stop losses

3. Added `FullPrice` and `PriceLevel` structs in `trades.go` for detailed pricing information.

## Documentation
1. Updated examples to reflect the need for a config and updated method names.

## Code Changes
1. `account.go`: Updated `GetAccountInstruments` method to correctly handle the API response structure.
2. Added streaming functionality in `streaming.go` (new file).
3. Created new test files for each major component of the library.
4. Updated error message in `instrument.go` to stay in line with best practices.
5. Updated order-related structs in `orders.go` to include more comprehensive OANDA API properties.
6. Enhanced trade-related structs in `trades.go` with additional fields and new structures for detailed trade information.

## Breaking Changes
1. `trades.go` Updated the `RecievedTrade` Trades property name to Trade to reflect a single trade being returned

## Next Steps
- Ensure all new streaming functionality is properly documented.
- Consider adding more comprehensive error handling for streaming operations.
- Review and potentially expand test coverage for edge cases in streaming functionality.
- Update documentation to reflect the expanded capabilities of the order and trade-related structs.
- Consider implementing more integration tests to cover the new fields and structures in orders and trades.
- Review and update any client code that may be affected by the expanded struct definitions.

### CODE REVIEW

**Comment by jSydorowicz21** [comment]
Will merge this after some additional live testing with the new order body properties

**Comment by AwolDes** [comment]
@jSydorowicz21 great test coverage!

**Comment by jSydorowicz21** [comment]
> @jSydorowicz21 great test coverage!

Thank you! Figured I'd knock off the remainder of the original to do list and add in some stuff I was missing myself like take profit orders while I had some free time. Will need some inspiration from the community on any more features because I'm about out of ideas

**Comment by jSydorowicz21** [comment]
@AwolDes I don't have permissions to myself, would you mind editing the repo description to something a little more simplified and descriptive of the new supported streaming functionality? Something along the lines of "A Go package for interacting with Oanda's Forex REST and Streaming API" should work

**Comment by AwolDes** [comment]
> @AwolDes I don't have permissions to myself, would you mind editing the repo description to something a little more simplified and descriptive of the new supported streaming functionality? Something along the lines of "A Go package for interacting with Oanda's Forex REST and Streaming API" should work

Done 👍

**Pull request merged**
